//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_kpi_joPerYeardetails_Result
    {
        public Nullable<int> totayl { get; set; }
        public Nullable<int> jo_yr { get; set; }
        public Nullable<int> jo_ontime { get; set; }
        public Nullable<int> jo_delayed { get; set; }
        public Nullable<int> jo_ongoing { get; set; }
        public Nullable<int> jo_unassigned { get; set; }
    }
}
