//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_jo_sw_stages_and_issues_Result
    {
        public string job_no { get; set; }
        public Nullable<System.DateTime> date_filed { get; set; }
        public string application_name { get; set; }
        public string assignee { get; set; }
        public string status { get; set; }
    }
}
