//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_jo_time_allocation_Result
    {
        public Nullable<int> details_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string day { get; set; }
        public Nullable<int> mins { get; set; }
        public string work_description { get; set; }
    }
}
