//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jo_creation_availability
    {
        public int jca_id { get; set; }
        public string can_create { get; set; }
        public string message { get; set; }
        public string temp_access { get; set; }
    }
}
