//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_preventive_diagnose
    {
        public int diagnose_id { get; set; }
        public int maintenance_id { get; set; }
        public Nullable<int> services_id { get; set; }
        public string remarks { get; set; }
        public string notes { get; set; }
        public string time_finish { get; set; }
    }
}
