//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category_type
    {
        public int type_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string code_number { get; set; }
        public string details { get; set; }
        public Nullable<int> standard_time { get; set; }
        public string is_active { get; set; }
    }
}
