//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ForApprovalJO
    {
        public string job_no { get; set; }
        public string details { get; set; }
        public string requested_by { get; set; }
        public string jo_status { get; set; }
        public string noted_by_sign { get; set; }
        public string approved_by_sign { get; set; }
        public int jobno_id { get; set; }
    }
}
