//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Managers
    {
        public int emp_no { get; set; }
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string dept_id { get; set; }
        public string position { get; set; }
    }
}
