//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_hardware_counts_Result
    {
        public string hw_codenumber { get; set; }
        public Nullable<int> count_email { get; set; }
        public Nullable<int> count_tel { get; set; }
        public Nullable<int> count_desktop { get; set; }
        public Nullable<int> count_network { get; set; }
        public Nullable<int> standard_time { get; set; }
        public Nullable<int> actual_time { get; set; }
    }
}
