//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_export_excel_Result
    {
        public string department { get; set; }
        public Nullable<System.DateTime> date_filed { get; set; }
        public string jo_no { get; set; }
        public string details { get; set; }
        public string apc { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_ended { get; set; }
        public Nullable<int> hrs_mins { get; set; }
        public string jo_status { get; set; }
        public string costcenter { get; set; }
        public Nullable<int> details_id { get; set; }
    }
}
