//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_kpi_resource_utilization_Result
    {
        public string emp_name { get; set; }
        public Nullable<int> jo_count { get; set; }
        public Nullable<int> jo_actual { get; set; }
        public Nullable<int> report_count { get; set; }
        public Nullable<int> report_mins { get; set; }
    }
}
