//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_kpi_hardware_Result
    {
        public Nullable<int> avg_actualtime { get; set; }
        public Nullable<int> avg_standard { get; set; }
        public Nullable<decimal> percent_actualtime { get; set; }
        public Nullable<int> total_actual { get; set; }
        public Nullable<int> tota_standard { get; set; }
    }
}
