//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_sw_jo_issues_Result
    {
        public Nullable<int> details_id { get; set; }
        public Nullable<System.DateTime> date_happen { get; set; }
        public string problem { get; set; }
        public string status { get; set; }
        public int p_ID { get; set; }
    }
}
