//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_get_all_actual_standard_time_Result
    {
        public int details_id { get; set; }
        public int actual_time { get; set; }
        public int standard_time { get; set; }
    }
}
