//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_assignee_ongoing_jo_Result
    {
        public string jobno { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> date_assigned { get; set; }
        public Nullable<System.DateTime> date_target { get; set; }
        public Nullable<int> progress_rate { get; set; }
        public string dept_name { get; set; }
        public Nullable<System.DateTime> date_progress_updated { get; set; }
        public Nullable<int> flg_due { get; set; }
        public string reason_of_due { get; set; }
    }
}
