//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_get_sbu_description_Result
    {
        public int sbu_id { get; set; }
        public string sbu { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public string division { get; set; }
    }
}
