//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_latest_available_apc_Result
    {
        public string emp_name { get; set; }
        public string latest_target { get; set; }
        public string emp_id { get; set; }
    }
}
