//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_tel_downtime_details_Result
    {
        public string tel_code_number { get; set; }
        public Nullable<System.DateTime> datestarted { get; set; }
        public Nullable<System.DateTime> dateended { get; set; }
        public Nullable<int> dowtime_mins { get; set; }
        public string downtime_cause { get; set; }
        public string downtime_cause_details { get; set; }
        public string downtime_location { get; set; }
        public string tel_name { get; set; }
    }
}
