//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_departments_softwares_Result
    {
        public string application_name { get; set; }
        public string code_number { get; set; }
        public string emp_name { get; set; }
        public string user_department { get; set; }
    }
}
