//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_all_apc_jo_count_Result
    {
        public string dev { get; set; }
        public Nullable<int> today_total { get; set; }
        public Nullable<int> overall_total { get; set; }
        public string dev_contact { get; set; }
        public Nullable<int> due_ongoing { get; set; }
        public Nullable<int> unachieved_jo { get; set; }
        public Nullable<int> achieved_jo { get; set; }
        public Nullable<int> total_completed { get; set; }
        public Nullable<int> jo_hw { get; set; }
        public Nullable<int> jo_sw { get; set; }
        public string emp_id { get; set; }
        public Nullable<int> assessment { get; set; }
    }
}
