//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Database
{
    using System;
    
    public partial class sp_get_myjo_summary_hw_Result
    {
        public string category { get; set; }
        public string jotype { get; set; }
        public Nullable<int> jocount { get; set; }
        public Nullable<int> Pending { get; set; }
    }
}
